import { cleanPsychArticles } from './dataCleaners';
import { mockArticles } from '../apiCalls/mockArticles';

describe('cleanPsychArticles', () => {
  it('returns an object with correct data', async () => {
    const expected = [ { author: 'Ewan Murray at Carnoustie',
    description: 'The Open champion spent mid-May searching for answers after missing the cut at the Players Championship. At Carnousie he bagged his first major Two months can be a long time in golf. Just ask the new holder of the Claret Jug, Francesco Molinari. It seems incr…',
    publishedAt: '2018-07-23T14:32:09Z',
    source: { id: 'the-guardian-au', name: 'The Guardian (AU)' },
    title: 'How Francesco Molinari went from missed cuts to Claret Jug – in eight weeks',
    url: 'https://www.theguardian.com/sport/2018/jul/23/francesco-molinari-missed-cuts-claret-jug-eight-weeks',
    urlToImage: 'https://i.guim.co.uk/img/media/3d5ee83d0ce0fecada3d93c4c512063d6f14f715/0_0_4866_2920/master/4866.jpg?w=1200&h=630&q=55&auto=format&usm=12&fit=crop&crop=faces%2Centropy&bm=normal&ba=bottom%2Cleft&blend64=aHR0cHM6Ly9hc3NldHMuZ3VpbS5jby51ay9pbWFnZXMvb3ZlcmxheXMvZDM1ODZhNWVmNTc4MTc1NmQyMWEzYjYzNWU1MTcxNDEvdGctZGVmYXVsdC5wbmc=&s=64f57a8fdb8afe2b2812cac03c294565' },
  { author: 'EditorDavid',
    description: 'Long-time Slashdot reader RoccamOccam summarizes an article now circulating on the web sites of several schools: Child and adolescent psychologist Richard Freed writes, "...parents have no idea that lurking behind their kids\' screens and phones are a multitud…',
    publishedAt: '2018-07-21T20:34:00Z',
    source: { id: null, name: 'Slashdot.org' },
    title: 'The Tech Industry\'s War On Kids',
    url: 'https://tech.slashdot.org/story/18/07/21/2029204/the-tech-industrys-war-on-kids',
    urlToImage: 'https://a.fsdn.com/sd/topics/social_64.png' },
  { author: 'Meghan Cook',
    description: 'Relationships that begin in friendship can be rewarding and comfortable because you already know each other’s imperfections and flaws and love each other all the more in spite of them. The most difficult aspect of transitioning from friendship to coupledom is…',
    publishedAt: '2018-07-20T14:33:30Z',
    source: { id: null, name: 'Thisisinsider.com' },
    title: '7 signs your friend is in love with you',
    url: 'https://www.thisisinsider.com/signs-your-friend-wants-to-be-more-2018-7',
    urlToImage: 'https://static.businessinsider.com/image/5b51f2cc42e1cc339170e01c-750.jpg' },
  { author: 'Lindsay Dodgson',
    description: 'Sex is pretty important for the majority of people in intimate relationships. According to psychologist Madeleine A. Fugère, there are four scientific ways sex brings couples closer together. Sex is a vital part of romantic relationships for many people, apar…',
    publishedAt: '2018-07-20T11:54:00Z',
    source: { id: null, name: 'Thisisinsider.com' },
    title: '4 ways sex brings couples closer to each other, according to science',
    url: 'https://www.thisisinsider.com/how-sex-makes-couples-closer-2018-7',
    urlToImage: 'https://amp.businessinsider.com/images/5b51cd877708e939cf35e6dd-1136-568.jpg' },
  { author: 'Lydia Belanger',
    description: 'It\'s normal to aspire to do more than you could ever get done. Don\'t beat yourself up about it.',
    publishedAt: '2018-07-23T13:45:00Z',
    source: { id: null, name: 'Entrepreneur.com' },
    title: 'Why You Shouldn\'t Feel Guilty If Your To-Do List Only Gets Longer',
    url: 'https://www.entrepreneur.com/article/317127',
    urlToImage: 'https://assets.entrepreneur.com/content/3x2/2000/20180720190726-GettyImages-696959540.jpeg' },
  { author: 'Gemma Went',
    description: 'Don\'t let your negative beliefs hold you back.',
    publishedAt: '2018-07-23T15:30:00Z',
    source: { id: null, name: 'Entrepreneur.com' },
    title: '5 Belief Shifts That Will Take You From Stagnating to Soaring',
    url: 'https://www.entrepreneur.com/article/316868',
    urlToImage: 'https://assets.entrepreneur.com/content/3x2/2000/20180719194138-GettyImages-733933545.jpeg' },
  { author: 'Cory Doctorow',
    description: 'The Chronicle of Higher Education profiles LiAnna Davis, Wikipedia Education\'s director, who forges alliance with colleges and their faculty. (more…)',
    publishedAt: '2018-07-23T18:05:32Z',
    source: { id: null, name: 'Boingboing.net' },
    title: 'Higher ed and Wikipedia go great together',
    url: 'https://boingboing.net/2018/07/23/wikinost.html',
    urlToImage: 'https://media.boingboing.net/wp-content/uploads/2018/07/1122px-Wikipedia-logo-v2.svg_.png.jpg' },
  { author: 'Bastiaan T Rutjens',
    description: 'Climate change is particularly polarizing around a left-right divide, but most questions of scientific accuracy come down to religion and scientific literacy. Today, there is a crisis of trust in science. Many people–including politicians and, yes, even presi…',
    publishedAt: '2018-07-23T13:00:54Z',
    source: { id: null, name: 'Fastcompany.com' },
    title: 'Distrust of science isn’t just about left vs. right',
    url: 'https://www.fastcompany.com/90205244/distrust-of-science-isnt-just-about-left-vs-right?partner=feedburner&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+fastcompany%2Fheadlines+%28Fast+Company%29',
    urlToImage: 'https://images.fastcompany.net/image/upload/w_1280,f_auto,q_auto,fl_lossy/wp-cms/uploads/2018/07/p-1-90205244-what-makes-people-distrust-science-surprisingly-not-politics.jpg' },
  { author: 'Ed Yong',
    description: 'Researchers have found 1,271 gene variants associated with years of formal schooling. That’s important, but not for the obvious reasons.',
    publishedAt: '2018-07-23T15:00:00Z',
    source: { id: null, name: 'Theatlantic.com' },
    title: 'Why Study the Genetics of Staying in School?',
    url: 'https://www.theatlantic.com/science/archive/2018/07/staying-in-school-genetics/565832/',
    urlToImage: 'https://cdn.theatlantic.com/assets/media/img/mt/2018/07/GettyImages_182601325/facebook.jpg?1532350514' },
  { author: 'https://www.facebook.com/bbcnews',
    description: 'A jailed Pussy Riot activist describes how he and others got onto the pitch in police uniform.',
    publishedAt: '2018-07-21T01:33:18Z',
    source: { id: 'bbc-news', name: 'BBC News' },
    title: 'Russia World Cup: How Pussy Riot managed to burst into final',
    url: 'https://www.bbc.co.uk/news/world-europe-44886550',
    urlToImage: 'https://ichef.bbci.co.uk/news/1024/branded_news/CB35/production/_102612025_pussylovreut15jul18.jpg' },
  { author: null,
    description: '“How do I double click?” “What is a cell in a spreadsheet?”Mashiko Ishii often hears that her fellow',
    publishedAt: '2018-07-22T11:31:27Z',
    source: { id: null, name: 'Asahi.com' },
    title: 'A new digital divide: Young people who can’t use keyboards',
    url: 'http://www.asahi.com/ajw/articles/AJ201803290068.html',
    urlToImage: 'http://www.asahicom.jp/ajw/articles/images/AS20180329005166_comm.jpg' },
  { author: 'http://www.facebook.com/neurosciencenews',
    description: 'A new study reports on increased susceptibility to false memories after mindful meditation.',
    publishedAt: '2018-07-21T15:46:16Z',
    source: { id: null, name: 'Neurosciencenews.com' },
    title: 'Mindfulness May Make Memories Less Accurate',
    url: 'https://neurosciencenews.com/false-memory-mindful-meditation-psychology-2605/',
    urlToImage: 'https://i2.wp.com/neurosciencenews.com/files/2015/09/mindfulness-false-memory.jpg?fit=560%2C625&ssl=1' },
  { author: null,
    description: 'Comments',
    publishedAt: '2018-07-23T02:58:42Z',
    source: { id: null, name: 'Wikipedia.org' },
    title: 'Street dogs in Moscow learn to ride the subway',
    url: 'https://en.wikipedia.org/wiki/Street_dogs_in_Moscow',
    urlToImage: null },
  { author: 'Hannah Allam',
    description: 'It’s hard enough dealing with the suicide of a loved one, but for a lot of Muslim families, that’s just the beginning of the heartache. View Entire Post ›',
    publishedAt: '2018-07-21T16:01:03Z',
    source: { id: null, name: 'Buzzfeednews.com' },
    title: 'These Muslims Are Fighting Stigma After Losing Loved Ones To Suicide',
    url: 'https://www.buzzfeednews.com/article/hannahallam/suicide-rate-rising-muslims-mental-health-stigma-haydar',
    urlToImage: 'https://img.buzzfeed.com/buzzfeed-static/static/2018-07/12/13/enhanced/buzzfeed-prod-web-05/original-4835-1531416501-5.jpg?crop=2000:1048;0,203' },
  { author: 'Brendan Caldwell',
    description: 'The monsters are sleeping. They stand around in dark corners, obscured by a thick dust that hangs in the air. Our squad creeps through the doorway, crouching and tense and heavily armed. Then: a single gunshot. The monsters are awake. They scream, they run at…',
    publishedAt: '2018-07-20T18:00:56Z',
    source: { id: null, name: 'Rockpapershotgun.com' },
    title: 'The cramped horror of GTFO hopes to bond people',
    url: 'https://www.rockpapershotgun.com/2018/07/20/the-cramped-horror-of-gtfo-hopes-to-bond-people/',
    urlToImage: 'https://assets.rockpapershotgun.com/images/2018/07/GTFO-preview-1b.jpg' },
  { author: 'John Walker',
    description: 'I know what you’re up to, “videogames”. I see you. I see what’s happening here. You think you’re getting away with it, but not on my watch buddy. Not on my foil-wrapped watch. Here are the top 10 games to watch out for this week.',
    publishedAt: '2018-07-23T13:00:51Z',
    source: { id: null, name: 'Rockpapershotgun.com' },
    title: 'Steam Charts: They Don’t Want You To Read This Edition',
    url: 'https://www.rockpapershotgun.com/2018/07/23/steam-charts-they-dont-want-you-to-read-this-edition/',
    urlToImage: 'https://assets.rockpapershotgun.com/images/2018/07/charts_clicker.jpg' },
  { author: 'Autoblog Staff',
    description: 'Filed under: Ownership, Car Buying They can save you money if you know what you\'re doing. Continue reading What is a new car incentive or rebate? What is a new car incentive or rebate? originally appeared on Autoblog on Fri, 20 Jul 2018 14:01:00 EDT. Please s…',
    publishedAt: '2018-07-20T18:01:00Z',
    source: { id: null, name: 'Autoblog.com' },
    title: 'What is a new car incentive or rebate?',
    url: 'https://www.autoblog.com/2018/07/20/incentive-rebate-apr-glossary/',
    urlToImage: 'https://o.aolcdn.com/images/dims3/GLOB/legacy_thumbnail/800x450/format/jpg/quality/85/http://o.aolcdn.com/hss/storage/midas/7cd7e8be6db4d6b1bff72ca385472433/201140069/118246488.jpg' },
  { author: null,
    description: 'Researchers who examined child speech interactions over the course of a year found that vulnerable children benefit from conversations with their peers and their teachers.',
    publishedAt: '2018-07-23T18:29:48Z',
    source: { id: null, name: 'Sciencedaily.com' },
    title: 'Importance of language development in low-income, high-risk children',
    url: 'https://www.sciencedaily.com/releases/2018/07/180723142948.htm',
    urlToImage: null },
  { author: null,
    description: 'New research highlights sex differences associated with dementia and Alzheimer\'s disease across the life course, including the first ever large-scale study of reproductive history and dementia risk in women.',
    publishedAt: '2018-07-23T18:28:14Z',
    source: { id: null, name: 'Sciencedaily.com' },
    title: 'Pregnancy and reproductive history may impact dementia risk, study suggests',
    url: 'https://www.sciencedaily.com/releases/2018/07/180723142814.htm',
    urlToImage: null },
  { author: null,
    description: 'A new study makes new insights into how we recognize facial expressions of emotion, which is critical for successful interactions in business, diplomacy, and everyday social exchange.',
    publishedAt: '2018-07-23T18:28:50Z',
    source: { id: null, name: 'Sciencedaily.com' },
    title: 'How we see others\' emotions depends on our pre-conceived beliefs',
    url: 'https://www.sciencedaily.com/releases/2018/07/180723142850.htm',
    urlToImage: '/images/2018/07/180723142850_1_540x360.jpg' } ]
    const result = await cleanPsychArticles(mockArticles.articles);

    expect(result).toEqual(expected);
  });
});